/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jegy;

import javax.swing.JOptionPane;

/**
 *
 * @author Tomi
 */
public class Jegyrendeles extends javax.swing.JFrame {

    /**
     * Creates new form Jegyrendeles
     */
    public Jegyrendeles() {
        
        
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTavolsag = new javax.swing.JTextField();
        cbKedvezmeny = new javax.swing.JComboBox<>();
        cbOsztaly = new javax.swing.JComboBox<>();
        btnKiszamol = new javax.swing.JButton();
        lblVegosszeg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jegyrendelés");

        jLabel1.setText("Távolság (km):");

        jLabel2.setText("Kedvezmény mértéke (%)");

        jLabel3.setText("Osztály:");

        txtTavolsag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTavolsagActionPerformed(evt);
            }
        });
        txtTavolsag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTavolsagKeyReleased(evt);
            }
        });

        cbKedvezmeny.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINCS", "50%", "90%" }));

        cbOsztaly.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.", "2." }));

        btnKiszamol.setText("Jegy ára");
        btnKiszamol.setEnabled(false);
        btnKiszamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiszamolActionPerformed(evt);
            }
        });

        lblVegosszeg.setForeground(new java.awt.Color(255, 0, 0));
        lblVegosszeg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVegosszeg.setText("Fizetendő összeg");
        lblVegosszeg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKiszamol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTavolsag, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(cbKedvezmeny, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbOsztaly, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lblVegosszeg, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTavolsag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbKedvezmeny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbOsztaly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnKiszamol)
                .addGap(18, 18, 18)
                .addComponent(lblVegosszeg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKiszamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiszamolActionPerformed
        // TODO add your handling code here:
        double kmdij = 30;
        int felar = 500;
        int alapdij = (int) Double.parseDouble(txtTavolsag.getText());
        
              if (cbKedvezmeny.getSelectedItem() == "NINCS" && cbOsztaly.getSelectedItem().equals("1.")){
            lblVegosszeg.setText(Integer.toString((int) ((alapdij*kmdij)+felar))+ " Ft");
        }
        else if(cbKedvezmeny.getSelectedItem() == "50%" && cbOsztaly.getSelectedItem().equals("1.")){
            lblVegosszeg.setText(Integer.toString((int) ((alapdij*kmdij)*0.5) +felar)+ " Ft");
        }
        else if (cbKedvezmeny.getSelectedItem() == "90%" && cbOsztaly.getSelectedItem().equals("1.")){
            lblVegosszeg.setText(Integer.toString((int) ((alapdij*kmdij)*0.10) +felar)+ " Ft");
        }
        else if (cbKedvezmeny.getSelectedItem() == "90%" && cbOsztaly.getSelectedItem().equals("2.")){
            lblVegosszeg.setText(Integer.toString((int) ((alapdij*kmdij)*0.10))+ " Ft");
        }
        else if(cbKedvezmeny.getSelectedItem() == "50%" && cbOsztaly.getSelectedItem().equals("2.")){
            lblVegosszeg.setText(Integer.toString((int) ((alapdij*kmdij)*0.5))+ " Ft");
        }
        else if(cbKedvezmeny.getSelectedItem() == "NINCS" && cbOsztaly.getSelectedItem().equals("2.")){
            lblVegosszeg.setText(Integer.toString((int) ((alapdij*kmdij))*1)+ " Ft");
          
        } 
        //JOptionPane.showMessageDialog(null, "Ezt írom az ablakba...", "Ez kerül a címsorba", JOptionPane.ERROR_MESSAGE);
        
        if (txtTavolsag.getText().equals("0")) {
            lblVegosszeg.setText("Minimum 1 km-t kell utaznod!");
            JOptionPane.showMessageDialog(null, "Minimum 1 km-t kell utaznod!", "Hiba!", JOptionPane.ERROR_MESSAGE);
            txtTavolsag.setText("");
            lblVegosszeg.setText("Fizetendő összeg");
        }
        

    }//GEN-LAST:event_btnKiszamolActionPerformed

    private void txtTavolsagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTavolsagActionPerformed
        // TODO add your handling code here:
        /*
        if (txtTavolsag.getText().isEmpty()) {
            btnKiszamol.setEnabled(false);
        }
        */
    }//GEN-LAST:event_txtTavolsagActionPerformed

    private void txtTavolsagKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTavolsagKeyReleased
        // TODO add your handling code here:
        
        if (txtTavolsag.getText().length()>0) {
            btnKiszamol.setEnabled(true);
        }
        else btnKiszamol.setEnabled(false);
        /*
        if (txtTavolsag.getText()=="0") {
            btnKiszamol.setEnabled(false);
        }
        else btnKiszamol.setEnabled(true);
        */
    }//GEN-LAST:event_txtTavolsagKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jegyrendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jegyrendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jegyrendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jegyrendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jegyrendeles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKiszamol;
    private javax.swing.JComboBox<String> cbKedvezmeny;
    private javax.swing.JComboBox<String> cbOsztaly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblVegosszeg;
    private javax.swing.JTextField txtTavolsag;
    // End of variables declaration//GEN-END:variables
}
